apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-loginapp

spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-app
  template:
    metadata:
      labels:
        app: login-app

    spec:
      containers:
        - name: loginapp
          image: myloginapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP